### ISSUE TITLE
Doesn't work with celery send_task or named signatures

### ISSUE THREAD

**Issue by geniass** [Workable/flask-log-request-id#31]
For my use case, I need to call celery tasks by name rather than importing the actual task object.

It seems like this never calls the `apply_async` method, so the request ID is never set in the headers.

I believe a better way to set the headers is using Celery's [signal system](https://github.com/celery/celery/blob/v4.1.0/docs/userguide/signals.rst). Specifically the `before_task_publish` hook.

 I will open a pull request shortly.

**Comment by sque** [comment]
I think this was addressed by #34
