### ISSUE TITLE
Remove "nose" and "flake8" from "setup_requires"

### ISSUE THREAD

**Issue by twosigmajab** [Workable/flask-log-request-id#37]
"nose" and "flake8" are currently incorrectly declared as setup_requires dependencies. "nose" should just be removed from setup_requires since it's already correctly listed as a "test" dependency in extras_require, and "flake8" should be moved to either the "test" extra or some new "lint" or "dev" extra.

Thanks for this project and happy new year!

**Comment by sque** [comment]
Hi @twosigmajab!

Thanks for noticing! Requirements inside the setup_requires are not added in the install requirements. In other words if you perform `pip install flask-log-request-id` it will *not* install the `nose` or `flake8` package. They are under `setup_requires` so that commands such a `python setup.py flake8` or `python setup.py test` can work properly.

**Comment by twosigmajab** [comment]
Thanks for replying, @sque. Please note that as per https://github.com/pypa/setuptools/issues/1684 `python setup.py test` is being deprecated, and I'd expect the same to be true of `python setup.py flake8`.

Some more context for why I opened this: Having these listed in your setup_requires is complicating some internal tooling that isn't handling this properly. Of course that part is not your problem, but in light of the above, I'd be curious if you'd prefer to use an alternative, non-deprecated spelling rather than `python setup.py ...`, and ease integration for any other users you may have like us as a side effect.

**Comment by sque** [comment]
Hey @twosigmajab, thanks for the reference to pypa discussion! I was not aware of this situation and I really need to update my self on the subject.
From a fast view on the subject it seems that there is a bit of fuzz on the community of what is the correct guidelines to implement this functionality.
> It is unclear how setuptools sub-commands will be handled in the future, especially the internal ones. e.g. pypa/setuptools#1684

I also understand that setuptools want to deprecate support for `test` command but not the `python setup.py ...` schema:
> There was a decent amount of resistance to this idea as you can see from this ticket and #931, but I think that at the end of the day setup.py test is out of scope for what we are interested in maintaining as part of setuptools

Looking in other big repositories it seems like they don't abandon the `test` subcommand but implementing either with the initial idea of using `tox` or with custom implementation

e.g. sqlalchemy
https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy-collectd/+/1395/1/setup.py

Finally as long as the `pypa` has not made a clear decision about what will be done in the future and there is not even a deprecation warning or a clear case that the current situation is incompatible with something I feel that there is no need to rush to change something.

But hey, that's only how I feel :)
