### ISSUE TITLE
Maintainer Request

### ISSUE THREAD

**Issue by halfdan** [Workable/flask-log-request-id#40]
Hello 👋 

@sque You seem to be the main contributor on this repository so pinging you directly.

I'm interested in helping fix some of the issues reported and move this project forward. We're using this module in production and #38 is currently blocking a small refactor. 

Would you consider opening this project up to other contributors / maintainers and/or transition ownership to someone who would actively maintain it?

**Comment by halfdan** [comment]
Since this is a project owned by Workable I'm also tagging @nikostoulas @alkiskal.

**Comment by sque** [comment]
Hi @halfdan! :wave: 
Apologies for the late response. The project is open to submit features, fixes to anyone. Giving maintainer status though would take some time.

In any case I will check the issue soon and push a new release.
